print("namaste")
print("file delete chesa and kottadi create chesa")
print("ela undi okay na?")
print("ninnu kuda add chesa")
print("nuv naaku whatsapp lo video pampinav adi chusi ipud ee code pettina")
print("jhdftyfvjvghvhvjvjhvhjvhjvhjvjv")
print("vcgfcdcdtcghvvfbybgybguyibuybguyguybguy")
